### ISSUE TITLE
关于自动添加staff行功能的优化建议

### ISSUE THREAD

**Issue by AlbertWZhang** [Icexbb/SekaiSubtitle-Python#11]
建议优化staff行添加功能，自动从sekai text翻译文件提取该话标题，建议支持从excel中复制一整行粘贴至软件内自动读取staff表

**Comment by Icexbb** [comment]
updated in [a31f134](https://github.com/Icexbb/SekaiSubtitle-Python/commit/a31f13414de313421781b11711261a1c9ac450c3)
粘贴2~7个单元格的内容可以直接识别并填入
