### ISSUE TITLE
关于对话遮罩时间连续性的问题

### ISSUE THREAD

**Issue by AlbertWZhang** [Icexbb/SekaiSubtitle-Python#12]
建议增加检测功能，检测对话遮罩时间连续性（或者直接合并一整段对话的遮罩，就像Jeun版轴机那样）

**Comment by Icexbb** [comment]
该功能已经存在 5帧以内的会连起来

**Comment by AlbertWZhang** [comment]
并非指此功能，在88-1的轴中出现过个别两个遮罩间隔为0.01s的情况

**Comment by Icexbb** [comment]
目前版本使用的连续化功能会直接将上一个event的结束时间设为本帧event的开始时间 不会产生因为帧到时间戳的计算问题导致的差别
但是若该event为一个抖动event 该功能因为抖动event的特殊性无法生效 需要后续进行讨论
