### ISSUE TITLE
SEKAI Text无法选择json

### ISSUE THREAD

**Issue by Hart-160** [Icexbb/SekaiSubtitle-Python#20]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 Sekai Subtitle 上
- [X] 这个问题出现了至少3次
- [ ] 我使用过旧版的 Sekai Subtitle 并且没有出现过这个问题

### 描述你的问题

在翻译栏中，点选“载入”时本应选择json或assets文件，打开的file dialog却没有看到json文件，只能看到文件夹

### 如何复现

- 点选“翻译”栏
- 点选“载入”
- 有json文件的目录没有json文件显示

**Comment by Icexbb** [comment]
Fixed 
已在 5177355d2493d8000b012055683a6056350cc933 中修复 
请等待0.8.3版本发布
