### ISSUE TITLE
窗口爆闪乱抖

### ISSUE THREAD

**Issue by AlbertWZhang** [Icexbb/SekaiSubtitle-Python#23]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 Sekai Subtitle 上
- [X] 这个问题出现了至少3次
- [X] 我使用过旧版的 Sekai Subtitle 并且没有出现过这个问题

### 描述你的问题

当拖拽窗口时，窗口位置乱跳

### 如何复现

1. 打开软件
2. 拖拽窗口
3. 出现问题

### 截图

https://user-images.githubusercontent.com/47438714/229328988-34792996-e8a0-43dc-b4df-b05d8970da93.mp4

### 还有别的吗？

Microsoft Windows 11 家庭中文版
10.0.22621 版本 22621
OMEN by HP Laptop 16-b0xxx
基于 x64 的电脑
11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

**Comment by Icexbb** [comment]
这是更底层的问题（Windows/qt框架） 我也没办法
