### ISSUE TITLE
地点文字时间太短

### ISSUE THREAD

**Issue by Hart-160** [Icexbb/SekaiSubtitle-Python#25]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 Sekai Subtitle 上
- [X] 这个问题出现了至少3次
- [ ] 我使用过旧版的 Sekai Subtitle 并且没有出现过这个问题

### 描述你的问题

部分地点文字的显示时间只有20毫秒左右，本应有2秒多长度

### 如何复现

运行event_90_05，“赏花金鱼展”标题

**Comment by Icexbb** [comment]
与地点文字对应的遮罩是否与地点的时间长度一致？

**Comment by Hart-160** [comment]
文字和遮罩的时长是一样的，都只有一两帧长度
