### ISSUE TITLE
关于选择文件

### ISSUE THREAD

**Issue by LinQi2333** [Icexbb/SekaiSubtitle-Python#3]
1.在选择文件的时候加入一个拖入文件的功能
2.在选择文件的时候能记住上次选择文件的文件夹，而不是每次打开都默认程序所在的文件夹

**Comment by LinQi2333** [comment]
顺便加一个 选择其他功能模块时能不改变windows的大小

**Comment by Icexbb** [comment]
updated in [931fdce](https://github.com/Icexbb/SekaiSubtitle-Python/commit/931fdceea06bb17be8616e0d1791b236667d8df9)
release later
