### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by LinQi2333** [Icexbb/SekaiSubtitle-Python#4]
区域对话需要两个额外的样式如下
Style: staff - 左,思源黑体 CN Bold,70,&H00715659,&H000000FF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,5,5,7,30,10,30,1
Style: staff - 右,思源黑体 CN Bold,70,&H00715659,&H000000FF,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,5,5,9,10,30,30,1

**Comment by Icexbb** [comment]
updated in [7b3f57d](https://github.com/Icexbb/SekaiSubtitle-Python/commit/7b3f57df9fd03e657b04def972fbd0a640b2133d)
new release later

**Comment by Icexbb** [comment]
released in [v0.4.7](https://github.com/Icexbb/SekaiSubtitle-Python/releases/tag/v0.4.7)
