### ISSUE TITLE
自定义staff行

### ISSUE THREAD

**Issue by Hart-160** [Icexbb/SekaiSubtitle-Python#5]
因为第一行通常是staff行而现阶段轴机没有提供，所以希望轴机可以在开头添一行staff
希望的形式是：
- 活动剧情
`Dialogue: 0,0:00:00.00,0:00:05.00,staff,staff,0,0,0,,{\fad(0,200)\fs70}`

- 区域对话
`Dialogue: 0,0:00:00.00,0:00:05.00,staff - 左,staff,0,0,0,,{\fad(100,100)}`
`Dialogue: 0,0:00:00.00,0:00:05.00,staff - 右,staff,0,0,0,,{\fad(100,100)}`

可以试试一般剧情模式&区域对话模式分开？活动剧情那种就给前面的，区域对话那种给后边的？
然后staff行可以考虑在设置里自定义预设文本？
比如我自己会有这样的预设：
- 活动剧情
`字幕制作 by PJS字幕组\N第x话：\N录制：\N翻译：\N翻校：\N时轴：SEKAI的轴姬\N轴校&压制：`

- 区域对话
`\N录制：\N时轴：\N翻译：`
`图鉴位置\N\N\N\N`

**Comment by Icexbb** [comment]
updated in [7b3f57d](https://github.com/Icexbb/SekaiSubtitle-Python/commit/7b3f57df9fd03e657b04def972fbd0a640b2133d)
new release later

**Comment by Icexbb** [comment]
released in [v0.4.7](https://github.com/Icexbb/SekaiSubtitle-Python/releases/tag/v0.4.7)
